# Generated by Django 3.0.2 on 2020-01-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('user', models.EmailField(max_length=254)),
                ('lastModified', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
