# Generated by Django 3.0.2 on 2020-01-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudx', '0002_auto_20200120_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cloudx.UserDetails'),
        ),
    ]
